Create DataFrame

In [52]:
import pandas as pd

# create a data frame
print("# Show entire DataFrame")
data_cols = ["Name", "Class", "Score1"]
data_rows = [["Ellan", "CS", 87], ["Andrew", "Art", 98], ["Boby", "Acting", 83], ["Aqira", "Art", 78]]
df = pd.DataFrame(data=data_rows, columns=data_cols)
df

# Show entire DataFrame

     Name   Class  Score1
0   Ellan      CS      87
1  Andrew     Art      98
2    Boby  Acting      83
3   Aqira     Art      78

In [72]:
# Create a new colum
df ["Score2"] = 84, 97, 67, 72
df ["Score3"] = 56, 86, 98, 70
df

     Name   Class  Score1  Score2  Score3
0   Ellan      CS      87      84      56
1  Andrew     Art      98      97      86
2    Boby  Acting      83      67      98
3   Aqira     Art      78      72      70

In [37]:
# show the first 2 elements of the DataFrame
print("# First 2 elements of the DataFrame")
df.head(2)

# First 2 elements of the DataFrame

   Score Class    Name
0     87    CS   Ellan
1     98   Art  Andrew