Create DataFrame

In [410]:
import pandas as pd

# create a data frame
print("# Show entire DataFrame")
data_cols = ["Name", "Class", "Score1"]
data_rows = [["Ellan", "CS", 87], ["Andrew", "Art", 98], ["Boby", "Acting", 83], ["Aqira", "Art", 78]]
df = pd.DataFrame(data=data_rows, columns=data_cols)
df

# Show entire DataFrame

     Name   Class  Score1
0   Ellan      CS      87
1  Andrew     Art      98
2    Boby  Acting      83
3   Aqira     Art      78

In [411]:
# Create a new colum
print("# Create a new column")
df["Score2"] = 84, 97, 67, 72
df["Score3"] = 56, 86, 98, 70
df["Total"] = df["Score1"] + df["Score2"] + df["Score3"]
# copy a DataFrame
df_copy = df.copy()
df

# Create a new column

     Name   Class  Score1  Score2  Score3  Total
0   Ellan      CS      87      84      56    227
1  Andrew     Art      98      97      86    281
2    Boby  Acting      83      67      98    248
3   Aqira     Art      78      72      70    220

In [412]:
# show the first 2 elements of the DataFrame
print("# First 2 elements of the DataFrame")
# df.head(2)
df.head(2)

# First 2 elements of the DataFrame

     Name Class  Score1  Score2  Score3  Total
0   Ellan    CS      87      84      56    227
1  Andrew   Art      98      97      86    281

In [413]:
#print out the copy of dataframe
print("# DataFrame before")
df_copy

# DataFrame before

     Name   Class  Score1  Score2  Score3  Total
0   Ellan      CS      87      84      56    227
1  Andrew     Art      98      97      86    281
2    Boby  Acting      83      67      98    248
3   Aqira     Art      78      72      70    220

In [414]:
print("# DataFrame after get Modify")
df.at[3,"Name"] = ["Carlos"]
df.at[3,"Class"] = ["Economy"]
df.at[3, "Score1"] = [90]
df.at[3, "Score2"] = [73]
df.at[3, "Score3"] = [83]
df.at[3, "Total"] = df["Score1"][3] + df["Score2"][3] + df["Score3"][3]

df

# DataFrame after get Modify

     Name    Class  Score1  Score2  Score3  Total
0   Ellan       CS      87      84      56    227
1  Andrew      Art      98      97      86    281
2    Boby   Acting      83      67      98    248
3  Carlos  Economy      90      73      83    246